
# ===============================
# CONFIG SERVER
# ===============================
spring.config.import=optional:configserver:http://localhost:8888

# ===============================
# EUREKA CONFIGURATIONS
# ===============================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Optional - show IP in Eureka
eureka.instance.prefer-ip-address=true

# ===============================
# API GATEWAY SUPPORT
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=Tarun@123

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# ACTUATOR CONFIGURATION
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Application Info
info.app.name=CurrencyExchangeService
info.app.description=Handles currency exchange operations.
info.app.version=1.0.0
info.author=Sathyatech

management.info.env.enabled=true

# ===============================
# REDIS CONFIGURATION
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=60000
spring.cache.redis.cache-null-values=false

# ===============================
# SPRING BOOT ADMIN CLIENT
# ===============================
spring.boot.admin.client.url=http://localhost:1111

# ===============================
# ZIPKIN & DISTRIBUTED TRACING
# ===============================
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# ===============================
# LOGGING FOR TRACE IDs
# ===============================
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]                   





poojitha.today.discount=20
